fix: update balsamic tags
Clinical-Genomics/hermes pull request #41
Opened 2021-11-15 15:01 UTC by ivadym

## Description

Update tags according to `BALSAMIC 8.x.x` features.

### How to prepare for test
- [ ] ssh to hasta.scilifelab.se
- [ ] Use stage: `us`
- [ ] paxa the environment: `paxa`
- [ ] install on stage (example for hasta):
`bash /home/proj/production/servers/resources/hasta.scilifelab.se/update-hermes-stage.sh [THIS-BRANCH-NAME]`

### How to test
- [ ] do ...

### Expected test outcome
- [ ] check that ...
- [ ] Take a screenshot and attach or copy/paste the output.

## Review
- [ ] code approved by
- [ ] tests executed by
- [ ] "Merge and deploy" approved by
Thanks for filling in who performed the code review and the test!

### This [version](https://semver.org/) is a
- [ ] **MAJOR** - when you make incompatible API changes
- [ ] **MINOR** - when you add functionality in a backwards compatible manner
- [ ] **PATCH** - when you make backwards compatible bug fixes or documentation/instructions

## Implementation Plan
- [ ] Document in ...
- [ ] Deploy this branch
- [ ] Inform to ...

2021-11-16 15:42 UTC, ivadym commented
- Update tags for WGS TUMOR_ONLY CASE.
- Update tags for WGS TUMOR_NORMAL CASE.

<img width="2338" alt="Screen Shot 2021-11-16 at 16 41 01" src="https://user-images.githubusercontent.com/26309194/142016927-8baa19f0-aaaa-40c1-ba72-8d2746d6627c.png">

2021-11-17 15:03 UTC, ivadym commented
Updated tags for `PANEL TUMOR_ONLY`, `PANEL TUMOR_NORMAL`, `PANEL UMI TUMOR_NORMAL` and `PANEL UMI TUMOR_ONLY` cases.

The tags `{"tmb", "stat-somatic-tmb", "vardict"}` have been removed as the balsamic rule (`vep_stat`) that was generating them no longer exists.

Tested on `hasta`:
<img width="2456" alt="Screen Shot 2021-11-17 at 15 53 25" src="https://user-images.githubusercontent.com/26309194/142225445-ae94fa0a-3631-4476-941b-30de4419b89d.png">

2021-11-17 15:39 UTC, ashwini06 requested changes
Look good 👍🏼

2021-11-17 15:39 UTC, ashwini06 commented on CHANGELOG.md
> +### Added
```suggestion
### Changed
```

2021-11-17 15:39 UTC, ashwini06 commented on CHANGELOG.md
> +- Update tags according to new BALSAMIC features
```suggestion
- Removed cnv tags from balsamic common tags
- Added cnv tags for balsamic panel (tumor-only and tumor-normal)
- Removed vardic tmb stat tags
```

2021-11-17 15:40 UTC, ashwini06 approved these changes

2021-11-22 08:12 UTC, Mropat approved these changes

2021-11-22 08:27 UTC, merged